version: "3"
services:
  chatgpt:
    image: yidadaa/chatgpt-next-web
    restart: always
    ports:
      - 3000:3000
  yakgpt:
    build:
      context: ./
    image: yakgpt/yakgpt:latest
    restart: always
    ports:
      - 3001:3000

